import { SiReact, SiCss } from "react-icons/si";
import { FaNodeJs, FaHtml5 } from "react-icons/fa";

export const technologies = [
    {
        id: "react-concepts",
        title: "React",
        slug: "react-concepts",
        navLabel: "React Concepts",
        href: "/react-concepts",
        shortDescription: "Hooks, State, Effects",
        longDescription: "Master React fundamentals, hooks, rendering, state management and performance.",
        icon: SiReact,
        cardBgClass: "bg-cyan-50",
        iconClass: "text-cyan-500",
        heroGradient: "bg-gradient-to-br from-cyan-400 via-sky-500 to-blue-600",
    },
    {
        id: "js-concepts",
        title: "JavaScript",
        slug: "js-concepts",
        navLabel: "JS Concepts",
        href: "/js-concepts",
        shortDescription: "Closures, Promises, ES6+",
        longDescription: "Master closures, promises, event loop and modern JavaScript.",
        icon: FaNodeJs,
        cardBgClass: "bg-yellow-50",
        iconClass: "text-yellow-500",
        heroGradient: "bg-gradient-to-br from-yellow-400 via-amber-400 to-orange-500",
    },
    {
        id: "html-questions",
        title: "HTML",
        slug: "html-questions",
        navLabel: "HTML",
        href: "/html-questions",
        shortDescription: "DOM, Forms, Accessibility",
        longDescription: "Learn semantic HTML, forms, accessibility and browser fundamentals.",
        icon: FaHtml5,
        cardBgClass: "bg-orange-50",
        iconClass: "text-orange-500",
        heroGradient: "bg-gradient-to-br from-orange-400 via-orange-500 to-red-600",
    },
    {
        id: "css-questions",
        title: "CSS",
        slug: "css-questions",
        navLabel: "CSS",
        href: "/css-questions",
        shortDescription: "Flexbox, Grid, Animations",
        longDescription: "Master Flexbox, Grid, positioning and responsive design.",
        icon: SiCss,
        cardBgClass: "bg-violet-50",
        iconClass: "text-violet-500",
        heroGradient: "bg-gradient-to-br from-violet-400 via-purple-500 to-blue-600",
    },
];
